#!/bin/bash

SCRIPT_DIR=$(dirname "$0")
php "$SCRIPT_DIR/../zfs-automount.php" unload_keys
exit_code=$?
if [ $exit_code -ne 0 ]; then
    logger -t zfs-automount "[error] Automount script exited with error code $exit_code"
    /usr/local/emhttp/webGui/scripts/notify -e "ZFS Automount" -d "Automount script exited with error code $exit_code" -i "alert"
fi