#!/bin/bash

SCRIPT_DIR=$(dirname "$0")
php "$SCRIPT_DIR/../zfs-automount.php" unmount_zvols
exit_code=$?
if [ $exit_code -ne 0 ]; then
    logger -t zfs-automount "[error] Script exited with error code $exit_code"
    /usr/local/emhttp/webGui/scripts/notify -e "ZFS Automount" -d "Script exited with error code $exit_code" -i "alert"
fi
