#!/bin/bash
#description=This script will take and manage the snapshots of ZFS datasets
#arrayStarted=true

# Run on schedule: 0 * * * *

nohup php /boot/config/plugins/zfs.automount/zfs.automount.php &