#!/bin/bash
#description=This script will configure the network interfaces on the server

# Run on schedule: At First Array Start Only

sysctl -p /boot/config/plugins/user.scripts/scripts/network-conf/sysctl.conf

ip rule add from 172.25.224.2 table 1
ip route add 172.25.224.0/24 dev br0 table 1 src 172.25.224.2
ip route add default via 172.25.224.1 dev br0 table 1 src 172.25.224.2

ip rule add from 172.25.224.128 table 2
ip route add 172.25.224.0/24 dev br1 table 2 src 172.25.224.128
ip route add default via 172.25.224.1 dev br1 table 2 src 172.25.224.128

# On Windows machines, the following routes are needed:
#  route /p add 172.25.224.2 mask 255.255.255.255 172.25.224.1 if XX
#  route /p add 172.25.224.128 mask 255.255.255.255 172.25.224.1 if YY
# Remove the /p option to make the route non-persistent
# The XX and YY interfaces can be found in the first column of the output of the command:
#  route print

arping -c 3 -U -I br0 172.25.224.2
arping -c 3 -U -I br1 172.25.224.128