#!/bin/bash

out="$(zfs unload-key -a 2>&1)"
if (($? == 0)); then
    logger -t "zfs_automount" "All keys unloaded"
else
    logger -p user.err -t "zfs_automount" "Failed to unload all keys: ${out}"
    exit 1
fi