#!/bin/bash

out="$(zfs unload-key -a 2>&1)"
if (($? == 0)); then
    logger -t "zfs_automount" "All ZFS encryption keys unloaded"
else
    msg="Failed to unload ZFS encryption keys: ${out}"
    /usr/local/emhttp/webGui/scripts/notify -s "ZFS Automount" -d "$msg" -i alert
    logger -p user.err -t "zfs_automount" "$msg"
    exit 1
fi