#!/bin/bash

abort() {
  /bin/echo "$1"
  /bin/echo "You will be dropped to a shell. Exit the shell to reboot."
  /bin/bash
  /bin/umount -a
  read -p "Press ENTER key to reboot..."
  /bin/echo
  /sbin/reboot -fd
}

find_device() {
  # find which USB flash device/partition has the indicated label
  local LABEL=$1
  local i
  for i in {1..30}; do
    DEVICE=$(/sbin/blkid -L "$LABEL")
    [[ -z $DEVICE ]] && /bin/sleep 1 || return 0
  done
  return 1
}

/sbin/mount -v -t proc proc /proc || abort "Cannot mount proc on /proc"
/sbin/mount -v -t sysfs sysfs /sys || abort "Cannot mount sysfs on /sys"
/sbin/mount -v -t tmpfs -o mode=0755,size=128M,nodev,nosuid,noexec tmpfs /run || abort "Cannot mount tmpfs on /run"
/sbin/mount -v -t devtmpfs -o size=8M devtmpfs /dev || abort "Cannot mount devtmpfs on /dev"

# prepare the UNRAID USB flash drive
UNRAID_LABEL="UNRAID"
/bin/echo -n "waiting up to 30 sec for device with label $UNRAID_LABEL to come online ... "
if find_device "$UNRAID_LABEL"; then
  /bin/echo "found $DEVICE"
else
  abort "not found"
fi
/bin/echo "Checking $DEVICE ..."
FSCK=$(/sbin/fsck.fat -a -w "$DEVICE" 2>/dev/null)
if [[ "$FSCK" == *"differences between boot sector and its backup"* ]]; then
  /sbin/fsck.fat -w "$DEVICE" 2>/dev/null <<<"1"
else
  /bin/echo "$FSCK"
fi
UNRAID_DEVICE=$DEVICE

# prepare the root device
ROOT_LABEL="ROOT"
/bin/echo -n "waiting up to 30 sec for device with label $ROOT_LABEL to come online ... "
if find_device "$ROOT_LABEL"; then
  /bin/echo "found $DEVICE"
else
  abort "not found"
fi
/sbin/btrfs device scan --all-devices || abort "cannot scan for BTRFS devices"
ROOT_DEVICE=$DEVICE

# mount root device
ROOT_DEVICE_MNT=/mnt/root_device
/bin/mkdir -p "$ROOT_DEVICE_MNT"
/sbin/mount -v -t btrfs -o auto,rw,noatime,degraded "$ROOT_DEVICE" "$ROOT_DEVICE_MNT" || abort "cannot mount $ROOT_DEVICE"

# snapshot the prod root subvolume
if /sbin/btrfs subvolume show "$ROOT_DEVICE_MNT/root-running" >/dev/null 2>&1; then
  /sbin/btrfs subvolume delete -c -R "$ROOT_DEVICE_MNT/root-running" || abort "cannot delete old root-running subvolume"
  /sbin/btrfs subvolume sync "$ROOT_DEVICE_MNT" || abort "cannot sync $ROOT_DEVICE_MNT"
fi
/sbin/btrfs subvolume snapshot "$ROOT_DEVICE_MNT/root/prod" "$ROOT_DEVICE_MNT/root-running" || abort "cannot create root-running snapshot"

# bind mount the new root
ROOT_MNT=/mnt/root
/bin/mkdir -p "$ROOT_MNT"
/sbin/mount -v --bind "$ROOT_DEVICE_MNT/root-running" "$ROOT_MNT" || abort "cannot bind mount $ROOT_DEVICE_MNT/root-running to $ROOT_MNT"

# mount the UNRAID USB flash into the new root
BOOT_MNT="$ROOT_MNT/boot"
/bin/mkdir -p "$BOOT_MNT"
/sbin/mount -v -t vfat -o auto,rw,flush,noatime,dmask=77,fmask=177,shortname=mixed "$UNRAID_DEVICE" "$BOOT_MNT" || abort "cannot mount $UNRAID_DEVICE"

# bind mount the config directory
mkdir -p "$BOOT_MNT/config"
/sbin/mount -v --bind "$ROOT_DEVICE_MNT/config" "$BOOT_MNT/config" || abort "cannot bind mount $ROOT_DEVICE_MNT/config to $BOOT_MNT/config"

# bind mount /root
mkdir -p "$BOOT_MNT/root"
/sbin/mount -v --bind "$ROOT_DEVICE_MNT/root" "$BOOT_MNT/root" || abort "cannot bind mount $ROOT_DEVICE_MNT/root to $BOOT_MNT/root"

/bin/umount -v "$ROOT_DEVICE_MNT" || abort "cannot unmount $ROOT_DEVICE_MNT"
exec /sbin/switch_root "$ROOT_MNT" /sbin/init "$@" || abort "cannot switch root to $ROOT_MNT"
